
#### GetCountries
GET http://localhost:8001/api/common/GetCountries
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFkbWluIiwiaWF0IjoxNjA0ODI4MzExfQ.Ns7Sqzmv-7nG_nxL46dPU_fO9tca0AsE_tA8j_sgPgw

#### GetStates

GET http://localhost:8001/api/common/GetStates?country_id=101
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFkbWluIiwiaWF0IjoxNjA0ODI4MzExfQ.Ns7Sqzmv-7nG_nxL46dPU_fO9tca0AsE_tA8j_sgPgw


#### GetCities

GET http://localhost:8001/api/common/GetCities?state_id=35
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFkbWluIiwiaWF0IjoxNjA0ODI4MzExfQ.Ns7Sqzmv-7nG_nxL46dPU_fO9tca0AsE_tA8j_sgPgw


############ AIMS_SECRET_TOKEN_GENERATION

GET http://localhost:8001/api/auth/GenerateAIMSToken
Content-Type: application/json

{
    "aims_secret" :"CLOUDVILLE_ADMIN_OAUTH_ACCOUNTSERVICE_BACKEND_API"
}

####### SIGNUP ##################

POST http://localhost:8001/api/user/signUp
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFkbWluIiwiaWF0IjoxNjA0ODI4MzExfQ.Ns7Sqzmv-7nG_nxL46dPU_fO9tca0AsE_tA8j_sgPgw

{
	"first_name" : "Cha",
	"last_name" : "J",
	"user_emailid" : "charlesj@testmail.com",
	"mobileno" : "123123",
	"password" : "charlestest"
           
}

####### SIGNIN ##################

POST http://localhost:8001/api/user/signIn
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFkbWluIiwiaWF0IjoxNjA0ODI4MzExfQ.Ns7Sqzmv-7nG_nxL46dPU_fO9tca0AsE_tA8j_sgPgw

{
	"userid" : "chaj",	
	"password" : "charlestest"
           
}