
#### GetCountries
GET http://localhost:8001/api/common/GetCountries
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFkbWluIiwiaWF0IjoxNjA0ODI4MzExfQ.Ns7Sqzmv-7nG_nxL46dPU_fO9tca0AsE_tA8j_sgPgw

#### GetStates

GET http://localhost:8001/api/common/GetStates?country_id=101
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFkbWluIiwiaWF0IjoxNjA0ODI4MzExfQ.Ns7Sqzmv-7nG_nxL46dPU_fO9tca0AsE_tA8j_sgPgw


#### GetCities

GET http://localhost:8001/api/common/GetCities?state_id=35
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFkbWluIiwiaWF0IjoxNjA0ODI4MzExfQ.Ns7Sqzmv-7nG_nxL46dPU_fO9tca0AsE_tA8j_sgPgw


############ AIMS_SECRET_TOKEN_GENERATION

GET http://localhost:8001/api/auth/GenerateAIMSToken
Content-Type: application/json

{
    "aims_secret" :"CLOUDVILLE_ADMIN_OAUTH_ACCOUNTSERVICE_BACKEND_API"
}

####### SIGNUP ##################

POST http://localhost:8001/api/user/signUp
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFkbWluIiwiaWF0IjoxNjA0ODI4MzExfQ.Ns7Sqzmv-7nG_nxL46dPU_fO9tca0AsE_tA8j_sgPgw

{
	"first_name" : "Rajesh",
	"last_name" : "Kumar",
	"user_emailid" : "rajeshk@testmail.com",
	"mobileno" : "123432123",
	"password" : "rajeshtest"
           
}

####### SIGNIN ##################

POST http://localhost:8001/api/user/signIn
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFkbWluIiwiaWF0IjoxNjA0ODI4MzExfQ.Ns7Sqzmv-7nG_nxL46dPU_fO9tca0AsE_tA8j_sgPgw

{
	"userid" : "chaj",	
	"password" : "charlestest"
           
}

####### AddStore ########################


POST http://localhost:8001/api/store/AddStore
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFkbWluIiwiaWF0IjoxNjA0ODI4MzExfQ.Ns7Sqzmv-7nG_nxL46dPU_fO9tca0AsE_tA8j_sgPgw

{
				"user_id" : "chaj",
                "store_name" : "Store1",
                "store_alias" :  "Store1",
                "street1" :   "test street1",
                "street2": "test street2",
                "country": "USA",
                "state" : "CHICAGO",
                "city" : "ILLINOS",
                "zipcode" : "05635",
                "store_landline" :  "2512125127",
                "store_tax_number" :  "125371523",
                "plan" : "basic"		
           
}


######################### GetStores ######################

GET http://localhost:8001/api/store/GetStores?user_id=vrd
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNoYWoiLCJpYXQiOjE2MDU0MzY5NDR9.XdR3j6Mxm_1f9qftng8wmKPDXU3913Eaf3zBCbXIN1k

######################### VerfiyUserEmail ######################

GET http://localhost:8001/api/user/VerifyUserEmail?email_id=rajeshkj@testmail.com
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFkbWluIiwiaWF0IjoxNjA0ODI4MzExfQ.Ns7Sqzmv-7nG_nxL46dPU_fO9tca0AsE_tA8j_sgPgw

####### AddInvoiceAddress ########################


POST http://localhost:8001/api/user/AddPaymentInvoiceAddress
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFkbWluIiwiaWF0IjoxNjA0ODI4MzExfQ.Ns7Sqzmv-7nG_nxL46dPU_fO9tca0AsE_tA8j_sgPgw

{
				
				"user_id" : "chaj",
                "first_name" : "Test User1",
                "middle_name" : "Test",
                "last_name" : "Test",
                "user_emailid" :   "charlesj@testmail.com",
                "mobileno": "1243512312",
                "addressline1" :  "test addressline1",
                "addressline2": "test addressline2",
                "country": "USA",
                "state" : "CHICAGO",
                "city" : "ILLINOS",
                "zipcode" : "05635" 	
           
}


####### AddCardDetail ########################


POST http://localhost:8001/api/user/AddCardDetail
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFkbWluIiwiaWF0IjoxNjA0ODI4MzExfQ.Ns7Sqzmv-7nG_nxL46dPU_fO9tca0AsE_tA8j_sgPgw

{
				
				"user_id" : "chaj",
                "nameoncard" : "CHARLES J",
                "cardnumber" : "1234567890123456",
                "expirydate" : "12/2023"
               	
           
}



#######  ResetPassword ########################


POST http://localhost:8001/api/user/ResetPassword
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFkbWluIiwiaWF0IjoxNjA0ODI4MzExfQ.Ns7Sqzmv-7nG_nxL46dPU_fO9tca0AsE_tA8j_sgPgw

{
				
				"email_id" : "rajeshk@testmail.com",
                "password" : "rajeshtest1"
           
}